config/routes.rb
FirstApp::Application.routes.draw do

  devise_for :users

  root 'welcome#index', as: :index

  get '/black', to: 'welcome#black', as: :black

  get '/about', to: 'welcome#about', as: :about

  resources :users do
    resources :bills
  end

  resources :bills do
    collection do
      post 'create_bill'
    end
  end

  resources :comments

end

app/models/bill.rb
class Bill < ActiveRecord::Base

  # Validations
  validates :name, presence: true, allow_blank: false
  validates :user_id, presence: true
  validates :date, presence: true
  validates :value, presence: true

  # Associations
  belongs_to :user
  has_many :comments, as: :commentable

  # Scopes
  default_scope { order('bills.date DESC') }

  scope :recent, -> {order('bills.date DESC').limit(5)}

  scope :recent_by_date, ->(date) {
    where("bills.date <= '#{ date.to_s(:db) }' ").order('bills.date DESC').limit(5)
  }

  # Public methods

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  # Validations
  validates :content, presence: true, allow_blank: false
  validates :commentable_id, presence: true
  validates :commentable_type, presence: true

  # Associations
  belongs_to :commentable, polymorphic: true

  # Scope
  default_scope {order('comments.created_at DESC')}

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  MALE = 1
  FEMALE = 2

  # Validations
  validates :name, presence: true, allow_blank: false
  validates :email, presence: true, allow_blank: false
  validates :gender, presence: true, :if => :adulthood
  validates :email, uniqueness: true

  # Associations
  has_many :bills, :dependent => :destroy
  has_many :comments, as: :commentable


  # Scopes

  # Callback
  after_create :send_welcome_email


  # Public Methods
  def adulthood
    self.age.present? and self.age >= 18
  end

  def send_welcome_email
    AppMailer::UserMailer.welcome_message(self.name, self.email).deliver
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:edit) { |u| u.permit(:name, :email, :password, :password_confirmation) }
  end

end

app/controllers/bills_controller.rb
class BillsController < ApplicationController

  def new
    @bill = Bill.new
    @users = User.all
  end

  def create_bill
    @bill = Bill.new(user_id: params[:user_id], name: params[:name] )
    @bill.description = params[:description]
    @bill.value = params[:value]
    @bill.date = params[:date]

    if @bill.save
      redirect_to @bill.user
    else
      @users = User.all
      render :new
    end

  end


  def create
    @bill = Bill.new(bill_params)
    flash[:notice] = (@bill.save ? t('saved_successfully') : t('error_while_saving'))
  end

  def destroy
    @bill = Bill.find(params[:id])
    @bill.destroy
  end

  def edit
    @bill = Bill.find(params[:id])
  end

  def update
    @bill = Bill.find(params[:id])
    flash[:notice] = (@bill.update(bill_params) ? t('saved_successfully') : t('error_while_saving'))
  end



private

  def bill_params
    params.require(:bill).permit(:name, :description, :date, :value, :user_id)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
    @comment.commentable_type = params[:commentable_type]
    @comment.commentable_id = params[:commentable_id]
  end


  def create
    @comment = Comment.new(comment_params)
    @comment.save
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
  end


private

  def comment_params
    params.require(:comment).permit(:content, :commentable_id, :commentable_type)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
    @users = User.all
  end


  def new
    @user = User.new
  end


  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'Usuário criado'
      redirect_to user_path(@user)
    else
      render :action => :new
    end
  end

  def show
    @user = User.find(params[:id])
  end


  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:notice] = 'Usuário atualizado'
      redirect_to @user
    else
      render :action => :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    flash[:notice] = (@user.destroy ? 'Usuário excluiído' : 'Falha na exclusão')
    redirect_to users_path
  end



private

  def user_params
    params.require(:user).permit(:name, :email, :age, :gender)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController


  before_filter :authenticate_user!, except: [:index, :black, :about]


  layout 'application_black', :only => [:black]

  def index
    @name = 'João Lucas'
    #debugger
  end

  def black   
   
  end


  def about
  
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bills/_bill.html.erb
<%= div_for(bill, class: 'well well-small') do %>
  <h4><%= bill.name %></h4>
  <%= bill.description %>

  <h5><%= l(bill.date, format: :long) %></h5>
  <h3><%= bill.value.round(2) %></h3>

  <%= link_to 'Editar', edit_user_bill_path(bill.user, bill), class: 'btn btn-primary', remote: true %>
  <%= link_to 'Remover', [bill.user, bill], class: 'btn btn-danger', remote: true, method: :delete, confirm: 'Tem certeza que deseja excluir?' %>

  <h3>Comentários</h3>
  <%= render partial: 'comments/index', locals: {commentable: bill} %>

<% end  %>

app/views/bills/_form.html.erb
<%= form_for([user, bill], remote: true) do |f| %>
  <%= render partial: 'shared/error_messages', locals: {resource: bill} %>

  <%= f.hidden_field :user_id, value: user.id %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :date %>
  <%= f.text_field :date%>

  <%= f.label :value %>
  <%= f.text_field :value %>

  <div class='form-actions'>
    <%= f.submit t('save'), class: 'btn btn-success' %>
  </div>
<% end %>

app/views/bills/_index.html.erb
<% if bills.any? %>

  <% bills.each do |bill| %>

    <%= render bill %>

  <% end %>


<% else %>

  <div class='alert'>
    <%= t('no_bills') %>
  </div>

<% end %>

app/views/bills/_new.html.erb
<hr/>

<h4><%= t('new_bill') %></h4>

<%= render partial: 'bills/form', locals: {bill: bill, user: user} %>

app/views/bills/create.js.erb
<% if @bill.persisted? %>
  $("#bills").html(" <%= j(render partial: 'bills/index', locals: {bills: @bill.user.bills}) %> ");
  $("new_bill").html("<%= j(render partial: 'bills/form', locals: {bill: Bill.new, user: @bill.user}) %>");
  $("#bill").prepend("<%= j notice %>");
<% else %>
  $("form.new_bill").html("<%= j(render partial: 'bills/form', locals: {bill: @bill, user: @bill.user}) %>");
<% end %>

app/views/bills/destroy.js.erb
<% if @bill.destroyed? %>
  $("#bill_<%= @bill.id %>").remove();
<% end %>

app/views/bills/edit.js.erb
$("#bill_<%= @bill.id %>").html("<%= j(render partial: 'bills/form', locals: {bill: @bill, user: @bill.user}) %>");

app/views/bills/new.html.erb
<br/><br/>
<h1><%= t('new_bill') %></h1>
<br/>

<%= form_tag(create_bill_bills_path) do %>

  <%= render partial: 'shared/error_messages', locals: {resource: @bill} %>

  <%= label_tag :user_id,  Bill.human_attribute_name(:user_id) %>
  <%= select_tag :user_id, options_from_collection_for_select(@users, :id, :name, @bill.user_id), prompt: 'Selecione um usuário'  %>

  <%= label_tag :name, Bill.human_attribute_name(:name) %>
  <%= text_field_tag :name, @bill.name %>

  <%= label_tag :description, Bill.human_attribute_name(:description) %>
  <%= text_field_tag :description, @bill.description %>

  <%= label_tag :date, Bill.human_attribute_name(:date) %>
  <%= text_field_tag :date, @bill.date %>

  <%= label_tag :value, Bill.human_attribute_name(:value) %>
  <%= text_field_tag :value, @bill.value %>

  <div class='form-actions'>
    <%= submit_tag 'Salvar', class: 'btn btn-success' %>
  </div>

<% end %>

app/views/bills/update.js.erb
<% if @bill.valid? %>
  $("#bill_<%= @bill.id %>").replaceWith("<%= j(render @bill) %>");
<% else %>
  $("#bill_<%= @bill.id %>").html("<%= j(render partial: 'bills/form', locals: {bill: @bill, user: @bill.user}) %>");
<% end %>

app/views/comments/_comment.html.erb
<%= div_for(comment) do %>

  <blockquote>
    <p>
      <%= comment.content %>
      <%= link_to "<i class='icon-remove icon-white'></i>".html_safe,
                  comment, remote: true, method: :delete,
                  class: 'btn btn-danger btn-mini pull-right' %>

      <%= link_to "<i class='icon-edit icon-white'></i>".html_safe,
                  edit_comment_path(comment), remote: true,
                  class: 'btn btn-primary btn-mini pull-right' %>
    </p>
  </blockquote>

<% end %>

app/views/comments/_form.html.erb
<%= form_for(comment, remote: true) do |f| %>
  <%= render partial: 'shared/error_messages', locals:{ resource: comment} %>
  <%= f.text_area :content, style: 'width:90%;' %>
  <%= f.hidden_field :commentable_type %>
  <%= f.hidden_field :commentable_id %>
  <br/>
  <%= f.submit 'Salvar', class: 'btn btn-success' %>
<% end %>

app/views/comments/_index.html.erb
<div id="commentable_<%= commentable.class %>_<%= commentable.id %>">

  <% if commentable.comments.any? %>

    <% commentable.comments.each do |comment| %>

      <%= render comment %>

    <% end %>

  <% else %>
    Não há comentários
  <% end %>


  <br/>
  <%= link_to "<i class='icon-comment icon-white'></i> Novo Comentário".html_safe,
              new_comment_path(commentable_type: commentable.class, commentable_id: commentable.id),
              class: 'btn btn-primary btn-small', remote: true %>

</div>

app/views/comments/_modal.html.erb
<div id='modal-comments' class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;
    </button>
    <h3>Comentário</h3>
  </div>
  <div class="modal-body">
    <%= render partial: 'comments/form', locals: {comment: comment} %>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn"  data-dismiss="modal" aria-hidden="true" >Close</a>
  </div>
</div>

app/views/comments/create.js.erb
<% if @comment.persisted? %>
  $("#modal-comments").modal('hide');
  <% index_content = j(render partial:'comments/index', locals: {commentable: @comment.commentable}) %>
  $("#commentable_<%= @comment.commentable.class %>_<%= @comment.commentable.id %>").replaceWith("<%= index_content %>");
<% else %>

<% end %>

app/views/comments/destroy.js.erb
<% if @comment.destroyed? %>
  $("#comment_<%= @comment.id %>").remove();
<% end %>

app/views/comments/edit.js.erb
<% edit_form = j(render partial: 'comments/form', locals: {comment: @comment}) %>
$("#comment_<%= @comment.id %>").html("<%= edit_form %>");

app/views/comments/new.js.erb
<% modal_content = j(render partial: 'comments/modal', locals:{comment: @comment}) %>
$("#modal-container").html("<%= modal_content %>");
$("#modal-comments").modal();

app/views/comments/update.js.erb
<% if @comment.valid? %>
  $("#comment_<%= @comment.id %>").replaceWith("<%= j(render @comment) %>");
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Título</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application"%>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render partial: 'shared/navbar' %>

  <div class='container'>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <div class='row-fluid'>

      <div class='span3'>
        <%= yield :sidebar %>
      </div>

      <div class='span9'>
        <%= yield %>
      </div>

    </div>

  </div>

  <div id='modal-container'></div>
</body>
</html>

app/views/layouts/application.js.erb
<%= yield %>

apply_mask();

app/views/layouts/email.html.erb
<html>
<head>
  <style type="text/css">
  html {-webkit-text-size-adjust:none;}
  body {background-color:#fff; padding:0;margin:0;width:100%;margin:0 auto;}
  .ReadMsgBody {width: 100%;}
  .ExternalClass {width: 100%;}
  *[class].tdwrap{display: inline-block !important;}
  *[class].vspacer{ margin-left: 50px; }
  @media all and (max-width: 590px){
    *[class].responsive{width:320px !important;}
    *[class].responsive-spacer table{width: 20px !important; }
    *[class].vspacer{ margin-top: 10px !important; margin-bottom: 15px !important; margin-left: 0 !important; }
    *[class].res-font16{font-size:16px !important;}
    *[class].res-font12{font-size:12px !important;}
  }
  </style>
</head>
<body >
  <table width="640" border="0" cellspacing="0" cellpadding="0" style="-webkit-border-radius: 5px;-moz-border-radius: 5px;border-radius: 5px;border:1px solid #29323d;text-align:left;margin: 0 auto;margin-top:10px;">
    <tbody style="font:normal 13px/16px Arial,Helvetica,sans-serif">
      <tr height="5">
        <td colspan="5" style="background-color:#29323d;"></td>
      </tr>
      <tr height="0"></tr>
      <tr style="height: 55px;" style="background-color:#29323d;">
        <td width="20" style="background-color:#29323d;"></td>
        <td width="300" style="background-color:#29323d">
          <div >
            asdf
          </div>
        </td>
        <td width="300" style="text-align:right ;background-color:#29323d;">
          
        </td>
        <td width="20" style="background-color:#29323d;"></td>
        <td width="20" style="background-color:#29323d;"></td>
      </tr>
      <tr height="20"></tr>
      <tr height="10">
        <td colspan="4" style="background-color: white;"></td>
      </tr>
      <tr height="20"></tr>
      <tr>
        <td width="20"></td>
        <td width="600" colspan="2">
 
          <p style="font-size:16px">
            <b><%= yield :title %></b>
          </p>
          <br>
          <p style="margin-top:40px">
            <span style="font-size:22px;font-family:arial,sans-serif"><span style="font-family:arial,sans-serif;color:#b6cc5d">✔</span> 
            <b style="line-height: 25px;"><%= yield :description %></b>
          </span>
        </p><ul style="padding:0;list-style:none">
 
        <li style="font-size:16px;overflow:hidden;border-bottom:1px dotted #d6d6d6;margin:0;padding:10px 15px">
          <b><%= yield :data %></b>
          <br>
        </li>
      </ul>
      <p></p>
      <br>
      <br>
      <br>
      <p>
        Atenciosamente,
        <br>
        <b>João Lucas</b>
      </p>
    </td>
    <td width="20"></td>
  </tr>
  <tr height="20"></tr>
  <tr height="43">
    <td colspan="5" style="background-color:#29323d;;border-top:1px solid #628cb0;border-bottom:1px solid #628cb0">
      <p style="text-align:center;font-size:12px;color:#fff">
        Assinatura
      </p>
    </td>
  </tr>
</tbody>
</table>  
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class='alert alert-error'>
    
    <h2> <%= pluralize(resource.errors.count, 'erro') %></h2>
    <ul>
      
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>

    </ul>

  </div>
  
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Nome do Projeto', index_path, class: 'brand' %>
      <div class="nav-collapse collapse">
        <p class="navbar-text pull-right">
          <% if user_signed_in? %>

            <ul class="nav pull-right">
              <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Welcome, <%= current_user.name %> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to "<i class='icon-cog'></i>Editar conta".html_safe,
                                edit_user_registration_path  %>
                  </li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "<i class='icon-off'></i> Logout".html_safe, 
                                destroy_user_session_path, method: :delete %>
                  </li>
                </ul>
              </li>
            </ul>

          <% else %>
            <%= link_to 'faça login', new_user_session_path, class: 'btn' %>
          <% end %>
        </p>
        <ul class="nav">
          <li class="active"><%= link_to 'Início', index_path %></li>
          <li><%= link_to 'Sobre', about_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<h3>Olá, <%= local_name %>, boa noite!</h3>

<div class="well sidebar-nav">
    <ul class="nav nav-list">
      <li class="nav-header">Sidebar</li>
      <li class="active"><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
      <li class="nav-header">Sidebar</li>
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
      <li class="nav-header">Sidebar</li>
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
    </ul>
  </div>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  
  <%= render :partial => 'shared/error_messages', :locals => {:resource => user} %>

  <div class='field'>
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>

  <div class='field'>
    <%= f.label :email %><br/>
    <%= f.email_field :email %>
  </div>

  <div class='field'>
    <%= f.label :age %><br/>
    <%= f.number_field :age %>
  </div>

  <div class='field'>
    <%= f.label :gender %><br/>
    <%= f.number_field :gender %>
  </div>

  <div class='form-actions'>
    <%= f.submit  'Salvar', :class => 'btn btn-primary' %>
    <%= link_to 'Voltar', users_path, :class => 'btn' %>
  </div>

<% end %>

app/views/users/edit.html.erb
<h4>Editar usuário</h4>

<%= render :partial => 'form', :locals => {:user => @user} %>

app/views/users/index.html.erb
<div class='alert alert-notice'><%= notice %></div>

<% if @users.any? %>

  <br/>
  <h1>Lista de usuários</h1>

  <table class='table table-bordered'>

    <% @users.each do |user| %>
      <tr>
        <td><%= link_to "#{user.name} #{user.email} - #{user.age}", user %></td>
        <td><%= link_to "<i class='icon-edit'> </i>".html_safe, edit_user_path(user) %></td>
        <td><%= link_to "<i class='icon-remove'></i>".html_safe, user, :method => :delete %></td>
      </tr> 
    <% end %>



  </table>

<% else %>
  
  <div class='alert'>
  
    Nenhum usuário cadastrado
  
  </div>

<% end %>


<%= link_to 'Novo usuário', new_user_path, class: 'btn btn-success' %>









<script type="text/javascript">

  $("#button").click(function(event, a, b, c) {

  });
</script>

app/views/users/new.html.erb
<h4>Novo usuário</h4>

<%= render :partial => 'form', :locals => {:user => @user} %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<p id='notice'><%= notice %> </p>

<p> <b>Nome:</b> <%= @user.name %> </p>
<p> <b>Email:</b> <%= @user.email %> </p>
<p> <b>Idade:</b> <%= @user.age %> </p>
<p> <b>Sexo:</b> <%= @user.gender %> </p>

  <h3>Comentários</h3>
  <%= render partial: 'comments/index', locals: {commentable: @user} %>

  <hr/>
  <% bill = Bill.new  %>

  <%= div_for bill do %>
    <%= render partial: 'bills/new', locals: {bill: bill, user: @user} %>
  <% end %>

  <div id='bills'>
    <%= render partial: 'bills/index', locals: {bills: @user.bills} %>
  </div>


<%= link_to 'Editar', edit_user_path(@user), :class => 'btn' %>
<%= link_to 'Voltar', users_path, :class => 'btn btn-danger' %>

app/views/welcome/about.html.erb
<h1>Sobre</h1>

<h5>Esta é uma aplicação Rails 4.0</h5>

app/views/welcome/black.html.erb
black

app/views/welcome/index.html.erb
<h1>Conteúdo central</h1>

<%= link_to 'Saiba mais sobre nós', about_path  %>

<br/>

<%= link_to 'Listar usuários', users_path, :class => 'btn btn-large' %>


<%= link_to t('new_bill'), new_bill_path, class: 'btn btn-large btn-success' %>


<%= content_for :sidebar do %>
  <%= render partial: 'shared/sidebar', locals: {local_name: @name} %>
<% end %>